#ifndef __CADDX_H__
#define __CADDX_H__

#define CADDX_START		0x7e
#define CADDX_START_ESC		0x20
#define CADDX_ACK_REQ		0x80
#define CADDX_MSG_MASK		0x3f

#define CADDX_IFACE_CFG		0x01
#define CADDX_ZONE_STATUS	0x04
#define CADDX_IFACE_CFG_REQ	0x21
#define CADDX_ACK		0x1d
#define CADDX_NAK		0x1e

#define CADDX_ZONE_FAULTED	BIT(0)
#define CADDX_ZONE_TAMPERED	BIT(1)
#define CADDX_ZONE_TROUBLE	BIT(2)
#define CADDX_ZONE_ACTIVITY	(CADDX_ZONE_FAULTED | CADDX_ZONE_TAMPERED | CADDX_ZONE_TROUBLE)

#endif /* __CADDX_H__ */
